<?php

namespace App\Services\Director;

enum BoundaryState: string
{
    case NOT_TESTED = 'NOT_TESTED';
    case MILD_TEST_OCCURRED = 'MILD_TEST_OCCURRED';
    case SALESPERSON_PARTICIPATED = 'SALESPERSON_PARTICIPATED';
    case INDIRECTLY_REDIRECTED = 'INDIRECTLY_REDIRECTED';
    case CLEAR_BOUNDARY_ESTABLISHED = 'CLEAR_BOUNDARY_ESTABLISHED';
    case CUSTOMER_RESPECTED_BOUNDARY = 'CUSTOMER_RESPECTED_BOUNDARY';
    case CUSTOMER_RETESTED_BOUNDARY = 'CUSTOMER_RETESTED_BOUNDARY';
    case SIGNIFICANT_VIOLATION = 'SIGNIFICANT_VIOLATION';
    case PROFESSIONAL_TERMINATION_ELIGIBLE = 'PROFESSIONAL_TERMINATION_ELIGIBLE';
}
