<?php

namespace App\Services\Director;

enum RoleplayEventType: string
{
    // Sales Communication Events
    case GOOD_OPENING = 'GOOD_OPENING';
    case WEAK_OPENING = 'WEAK_OPENING';
    case ACTIVE_LISTENING = 'ACTIVE_LISTENING';
    case INTERRUPTED_CUSTOMER = 'INTERRUPTED_CUSTOMER';
    case REPEATED_INTERRUPTION = 'REPEATED_INTERRUPTION';
    case CLEAR_EXPLANATION = 'CLEAR_EXPLANATION';
    case CONFUSING_EXPLANATION = 'CONFUSING_EXPLANATION';
    case GENERIC_SALES_SCRIPT = 'GENERIC_SALES_SCRIPT';
    case RELEVANT_FOLLOW_UP = 'RELEVANT_FOLLOW_UP';
    case MISSED_FOLLOW_UP = 'MISSED_FOLLOW_UP';
    case EMPATHIC_RESPONSE = 'EMPATHIC_RESPONSE';
    case DISMISSED_CONCERN = 'DISMISSED_CONCERN';
    case UNSUPPORTED_CLAIM = 'UNSUPPORTED_CLAIM';
    case CONTRADICTORY_STATEMENT = 'CONTRADICTORY_STATEMENT';
    case AGGRESSIVE_CLOSING = 'AGGRESSIVE_CLOSING';
    case APPROPRIATE_NEXT_STEP = 'APPROPRIATE_NEXT_STEP';
    case CHANGED_TOPIC_TOO_EARLY = 'CHANGED_TOPIC_TOO_EARLY';

    // Customer Concern Events
    case CONCERN_DISCOVERED = 'CONCERN_DISCOVERED';
    case OBJECTION_TRIGGERED = 'OBJECTION_TRIGGERED';
    case OBJECTION_ACKNOWLEDGED = 'OBJECTION_ACKNOWLEDGED';
    case OBJECTION_PARTIALLY_RESOLVED = 'OBJECTION_PARTIALLY_RESOLVED';
    case OBJECTION_RESOLVED_CANDIDATE = 'OBJECTION_RESOLVED_CANDIDATE';
    case MISCONCEPTION_CHALLENGED = 'MISCONCEPTION_CHALLENGED';
    case MISCONCEPTION_CLARIFIED_CANDIDATE = 'MISCONCEPTION_CLARIFIED_CANDIDATE';

    // Boundary Events
    case CUSTOMER_BOUNDARY_TEST = 'CUSTOMER_BOUNDARY_TEST';
    case SALESPERSON_PARTICIPATED_PERSONALLY = 'SALESPERSON_PARTICIPATED_PERSONALLY';
    case INDIRECT_REDIRECTION = 'INDIRECT_REDIRECTION';
    case CLEAR_PROFESSIONAL_REDIRECTION = 'CLEAR_PROFESSIONAL_REDIRECTION';
    case EXPLICIT_BOUNDARY_SET = 'EXPLICIT_BOUNDARY_SET';
    case CUSTOMER_RESPECTED_BOUNDARY = 'CUSTOMER_RESPECTED_BOUNDARY';
    case CUSTOMER_REPEATED_BOUNDARY_TEST = 'CUSTOMER_REPEATED_BOUNDARY_TEST';
    case SIGNIFICANT_BOUNDARY_VIOLATION = 'SIGNIFICANT_BOUNDARY_VIOLATION';

    // Conversation Events
    case CUSTOMER_BECAME_MORE_ENGAGED = 'CUSTOMER_BECAME_MORE_ENGAGED';
    case CUSTOMER_BECAME_LESS_ENGAGED = 'CUSTOMER_BECAME_LESS_ENGAGED';
    case CUSTOMER_CONFUSED = 'CUSTOMER_CONFUSED';
    case CUSTOMER_PRESSURED = 'CUSTOMER_PRESSURED';
    case TRUST_SIGNAL = 'TRUST_SIGNAL';
    case DISTRUST_SIGNAL = 'DISTRUST_SIGNAL';
}
